### ISSUE TITLE
nGrinder에 적용한 HttpClient 5

### ISSUE THREAD

**Issue by LeeJeongGi** [backend-tech-forge/benchmark#23]
어떻게 구현해야 하나 고민하고 있다가 nGrinder에서 사용하고 있는 방법 참고해서 해보려고 합니다!!

해당 내용 공유 드립니다. (이슈에 이런 공유글 올려도 되는걸까요,,,?)

https://d2.naver.com/helloworld/0881672

**Comment by ghkdqhrbals** [comment]
너무 좋은 내용 감사합니다 👍  아무거나 올리셔도 상관없습니다.

말씀주신 것 처럼 HttpClient 5, 또는 Reactor 라이브러리 기반 WebClient 이 둘 중 하나를 선택하는게 좋아보이네요.

> 테스트 동시성이 높은 동시성 만족을 위해 낮은 컨텍스트 스위칭 비용과 낮은 메모리 사용량을 제공하는 Java 21 virtual thread 를 이후에 고려해보면 좋겠네요! 만약 I/O 바운드 자체가 문제가 된다면 또 다른 방법을 생각해보겠습니다.

**Comment by ghkdqhrbals** [comment]
추가로 Java 에서 사용하는 HTTP 모듈 들을 가져와보았습니다.

* **RestTemplate** : blocking & synchronous
* **WebClient** : non-blocking & asynchronous(callback)
* **HttpClient 5** : non-blocking & asynchronous

[비교분석 자료](https://therealsainath.medium.com/resttemplate-vs-webclient-vs-httpclient-a-comprehensive-comparison-69a378c2695b)

**Comment by LeeJeongGi** [comment]
오! 영어를 보니 어지럽긴 하지만 천천히 한번 봐볼께요 :)

**Comment by ghkdqhrbals** [comment]
#36 에 병합합니다.
