### ISSUE TITLE
자바 비동기 처리 위해 사용하는 CompletableFuture class docs

### ISSUE THREAD

**Issue by LeeJeongGi** [backend-tech-forge/benchmark#35]
https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/CompletableFuture.html

Template vuser 만큼 쓰레드 생성해서 비동기 처리하기 위해 사용하는 CompletableFuture class docs 입니다.

**Comment by ghkdqhrbals** [comment]
감사합니다 😀

**Comment by ghkdqhrbals** [comment]
#36 에 병합합니다
