### ISSUE TITLE
동시성 향상을 위한 레퍼런스

### ISSUE THREAD

**Issue by ghkdqhrbals** [backend-tech-forge/benchmark#36]
## Async/Non-blocking Java method
* CompletableFuture : https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/CompletableFuture.html
* CompletableFuture cancel : https://stackoverflow.com/questions/65539126/whats-the-intended-pattern-of-canceling-already-running-completablefutures
> stage 가 끝나기 이전까진 취소 불가능

* CompletableFuture basic usage : https://mangkyu.tistory.com/263
> CompletableFuture 어떻게 사용해야 하는지 자세하게  코드 예시로 설명되어 있네요

## Async/Non-blocking HTTP 라이브러리
* WebClient : https://docs.spring.io/spring-framework/reference/web/webflux-webclient.html
* HttpClient5 : https://d2.naver.com/helloworld/0881672
* WebClient vs HttpClient5 : https://therealsainath.medium.com/resttemplate-vs-webclient-vs-httpclient-a-comprehensive-comparison-69a378c2695b

**Comment by LeeJeongGi** [comment]
CompletableFuture 기본적인 사용법 잘 정리된 블로그가 있어 공유드립니다 :)
