### ISSUE TITLE
Jacoco 테스트 커버리지 측정 시 Lombok 어노테이션으로 생성된 메서드 측정 제외 방법

### ISSUE THREAD

**Issue by ghkdqhrbals** [backend-tech-forge/benchmark#4]
## Description
> 사용된 버전은 lombok:1.18.2, jacoco:0.8.8 입니다.

보통 우리는 Lombok 을 통해서 Getter, Setter 등의 캡슐화 처리를 자동으로 진행합니다. 이 때 Jacoco 로 테스트 커버리지 측정 시 문제가 발생할 수 있습니다.

필요없는 set, get, toString, etc. 의 메서드들이 결과에 포함되어 실제로 원하는 커버리지와 다른 결과를 보여주기 때문입니다.

## How to Fix?

예를 들어, 아래의 BaseTime.class 를 볼까요?

<img width="884" alt="image" src="https://github.com/backend-tech-forge/benchmark/assets/29156882/d872f5a9-12ea-4f67-8879-fb10bfa9fd93">

<img width="890" alt="image" src="https://github.com/backend-tech-forge/benchmark/assets/29156882/d2f6f192-4b75-4c85-9140-398ddc719287">

필요없는 `setCreatedAt()`, `setUpdatedAt()` 이 Lombok 어노테이션으로 생성되어 이를 Jacoco 가 감지하고 결과에 넣는 모습을 볼 수 있습니다.

이를 방지할려면 프로젝트 루트 디렉토리에 lombok.config 파일을 생성한 뒤 내부에 `lombok.addLombokGeneratedAnnotation = true` 를 붙여주면 됩니다. Gradle 은 빌드 시 lombok.config 를 자동으로 읽어서 `@lombok.Generated` 를 모든 Lombok Annotation 위에 붙여주게 됩니다.

> `@lombok.Generated` 는 Getter, Setter 와 같은 자동 캡슐화 롬복 어노테이션을 실제로 명시적으로 나타내는 역할을 수행합니다.
>
> ```java
> // Origin Code
> @Getter
> public Class A {
>   private String id;
> }
> ```
> 
> ```java
> // Generated Code
> @Getter
> public Class A {
>   private String id;
> 
>   @lombok.Generated
>   public getId(){
>     return this.id;
>   }
> }
> ```

그러면 Jacoco 는 @lombok.Generated 어노테이션이 붙은 메소드를 커버리지 결과에서 제외시킵니다.

## Result

<img width="807" alt="image" src="https://github.com/backend-tech-forge/benchmark/assets/29156882/b4c5fd32-f960-427b-8fcf-ab55dce2c01c">

**Comment by LeeJeongGi** [comment]
오 좋은 정보 감사합니다!! 

롬복을 사용하면 편리하지만 남용은 하지 말아야 한다 라고 자주 이야기를 들었었는데, 
하지 말아야 하는 이유중에 이런 이유도 있겠네요. 😊

**Comment by ghkdqhrbals** [comment]
네 맞습니다. 롬복 사용 시 생성된 메소드들이 jacoco 테스트 커버리지에 불필요하게 포함되는 경우가 발생하거든요ㅜㅜ.

만약 jacoco:0.8.8 를 사용하신다면 루트 프로젝트에 `lombok.config` 파일을 만들고, 내부에 `lombok.addLombokGeneratedAnnotation = true` 를 적는다면 jacoco 가 알아서 롬복으로 생성된 메소드를 커버리지 결과에서 제외할 수 있습니다 👍
