### ISSUE TITLE
@TestContainer 사용 시 간헐적으로 컨테이너 다운이 안되는 문제

### ISSUE THREAD

**Issue by ghkdqhrbals** [backend-tech-forge/benchmark#50]
현재 저희가 `@TestContainer` 을 사용해서 테스트용 DB 를 띄우고 있습니다. 그런데 간간히 테스트 종료 후에도 컨테이너가 종료되지 않는 문제가 있습니다. 중간중간 확인해보셔야 할 것 같습니다. 아래는 지금까지 수많은 테스트를 진행하면서 종료되지 않은 누적된 컨테이너들입니다 :(

<img width="1366" alt="image" src="https://github.com/backend-tech-forge/benchmark/assets/29156882/bac4df9b-8b69-4751-a7ef-1327c931c64c">

**Comment by LeeJeongGi** [comment]
넵!! 테스트용 디비도 모니터링 해야겟네요

**Comment by ghkdqhrbals** [comment]
추가적으로 

<img width="560" alt="image" src="https://github.com/backend-tech-forge/benchmark/assets/29156882/13364971-7e61-4e8b-befe-760948ed5483">

@TestContainers 사용 도중 갑작스럽게 에러가 발생했습니다. 실제로 생성된 테스트 DB 컨테이너 내부 로그를 확인해보니 위와 같이 max-connection 보다 많은 접속이 이루어지고 있음을 확인하였습니다.ㅜㅜ

**Comment by LeeJeongGi** [comment]
설정상 디비 컨테이너가 새로생성되는게 아니라 업데이트 되는 방식으로 알고있었는데 왜 저렇게 많이 쌓였을까요,, 이유를 한번 알아봐야겠네요

**Comment by ghkdqhrbals** [comment]
> 설정상 디비 컨테이너가 새로생성되는게 아니라 업데이트 되는 방식으로 알고있었는데 왜 저렇게 많이 쌓였을까요,, 이유를 한번 알아봐야겠네요

터미널에서 `./gradlew testCoverageReport ` 시 중간에 강제 종료하게 되면 저런식으로 컨테이너가 종료되지 않더라구요. 해당 부분은 수정할 수 없을것 같습니다. 테스트 컨테이너 자체의 문제라서 변경할려면 실제 라이브러리를 뜯어봐야해요.
