### ISSUE TITLE
에러코드 관리 및 유연한 에러 메세지 추가

### ISSUE THREAD

**Issue by ghkdqhrbals** [backend-tech-forge/benchmark#84]
현재 에러코드가 enum 으로 사전정의되어있습니다. 그리고 내부 필드변수로 메세지또한 사전정의되어있습니다. 그래서 외부에서는 메세지를 추가할 수 없죠.

유연하게 메세지를 추가하고 싶었습니다. 예로 `ErrorCode.NO_USER` 이라면 어떤 유저가 없는지 메세지를 넣어주고 싶었어요.

그래서 `GlobalException.class` 에 내부 메세지 필드 변수 추가하고 이를 RestControllerAdvice 에서 ResponseEntity 변환 후 클라이언트에게 전송할 때 메세지 변수를 읽는 로직을 추가하였습니다.

**Comment by LeeJeongGi** [comment]
테스크 #84 연결 하신거 같은데,, 이거 pr 올리고 적용시킬수 있는걸까요?

**Comment by ghkdqhrbals** [comment]
네 PR 지금 올리겠습니다!

**Comment by LeeJeongGi** [comment]
연결 자체를 어떻게 한건지 물어본거였어요 ㅋㅋㅋ 저도 그 메일인증 테스크에 연결을 해보고싶어서요,,ㅎㅎ

**Comment by ghkdqhrbals** [comment]
> 연결 자체를 어떻게 한건지 물어본거였어요 ㅋㅋㅋ 저도 그 메일인증 테스크에 연결을 해보고싶어서요,,ㅎㅎ

혹시 redis 연결에 대해서 말씀하신거라면 docker compose 를 통해 띄우실 수 있습니다! 개별 컨테이너로 띄우는게 작업하시기 편하실거에요

**Comment by LeeJeongGi** [comment]
![image](https://github.com/backend-tech-forge/benchmark/assets/55478293/061dd142-381c-4ff9-9cd7-520c0e6af8db)

이슈랑 pr 이랑 연결해둔걸까요?

**Comment by ghkdqhrbals** [comment]
이슈로 올린 피쳐가 구현된 코드를 커밋할 때, 커밋 메세지에 이슈번호를 기술해둔것입니다 :)

**Comment by LeeJeongGi** [comment]
아하 커밋 메시지에 이슈번호를 기술하면 되는거였군요 
감사합니다!
